name: Vincero Nutrition
favicon: null
layout_spectrum: 0.07447929866611958
typography_spectrum: 0.09592485404573381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7075082340743393
  lightness: 0.2523116781376302
  saturation: 0.5496799619868398
  rhythmicContrast: 0.141986996633932
purpose: []
